version: '3'

services:
  php:
    build: docker/php
    restart: unless-stopped
    volumes:
      - .:/var/www/html              # must match vhost's DocumentRoot
    working_dir: /var/www/html       # commands run from this path
